packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  next: ^16.0.2
  typescript: ^5.9.2
  "@biomejs/biome": ^2.3.5

catalogs:
  react:
    "@types/node": ^20.19.9
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
    react: ^19.2.0
    react-dom: ^19.2.0